### ISSUE TITLE
Add MIT license so this can be upstreamed

### ISSUE THREAD

**Issue by toonsevrin** [jwallden/nebula-snap#1]
Great job! Could you perhaps add an MIT license so we can PR this upstream (or PR it upstream yourself)? :smile:

**Comment by jwallden** [comment]
Thank you for the interest and the input :smile: 
MIT license added!

I'd be happy to PR this upstream. How would I go about doing this?

**Comment by toonsevrin** [comment]
*Disclaimer: I'm not associated with slack :)*

Glad to hear! There's a dist folder with distribution files. You could create a snap folder there.

Personally I think, as they are distributions, the package should expose "nebula" "nebula-cert" and "nebula.daemon", they can be restricted by default (that way if people want more permissions they can connect HOME and whatnot).

I would place your snapcraft file in there, and a nice README explaining the different ways of running (daemon vs traditional, classic vs confined). A nice adition would also be to explain how to automatically launch the daemon on startup :+1: 

That's it! In the PR I would definitely also ask that they integrate this into their CD, ideally under the slack publisher.

Thank you for willing to do this :tada:

**Comment by toonsevrin** [comment]
I'd do it myself but I think that would require me to add your license in the snap directory, which I doubt they will want to merge :)

**Comment by jwallden** [comment]
I have now PR:ed this to Nebula. Let's see if they are interested :smile:
