### ISSUE TITLE
debian 10 error

### ISSUE THREAD

**Issue by GPConnect** [jwallden/nebula-snap#2]
Hello, 
thanks you for adopting nebula to snap ! it was the quickest way for me to try this mesh networking protocol !
i was able to use it without issue on an ubuntu 18.04 host but now i try to connect a debian 10 host but i get this error even with using sudo 

"level=fatal msg="failed to get tun device link: operation not permitted" 

can i have some help on this ? Thanks

**Comment by jwallden** [comment]
I'm glad it has come to use :)
Hmm. Seems strange that it doesn't work, even with sudo. Haven't been able to test it but do you have any more log output?

**Comment by GPConnect** [comment]
i used snap because i didn't know how to create a service to enable nebula ! it wasn't indicated in the doc ! i took a look around in the repo and found the service file ! so i use it as it should be on the debian host ! thanks again !

**Comment by adamwenner** [comment]
Doing a "snap install core" seemed to fix this issue for me on a Raspberry Pi OS (Raspbian) 10 system.

**Comment by jwallden** [comment]
Seems to be solved by @adamwenner 's way of doing it.
