### ISSUE TITLE
Update to version 1.4.0 of nebula

### ISSUE THREAD

**Issue by SirRujak** [jwallden/nebula-snap#3]
I know you have been trying to get this upstreamed but I wanted to mention that version 1.4.0 of nebula released yesterday and see if you were still planning on updating this repository. Thanks for any info!

**Comment by jwallden** [comment]
Hello!
Thanks for the notification. I have been tracking the Nebula release and my intention is to update the snap this time too. With a little bit of luck I can get it done this weekend depending on how much time I manage to free up. 

Regarding the PR to get this upstreamed i think they closed it. So the interest from the Nebula project to maintain a snap seems to be pretty low unfortunately.

**Comment by jwallden** [comment]
Finally got around to updating the snap today. Just built and released it now. Should be hitting your rig anytime now.
