### ISSUE TITLE
failed to load config: open /var/snap/nebula/common/config/config.yaml

### ISSUE THREAD

**Issue by Hooloovoo** [jwallden/nebula-snap#4]
Hello,

Thank you for making this. With the current lack of packages available, I wanted to use this to ensure my Nebula stays up to date.

When I try to run:
sudo nebula
though, I get a:
"failed to load config: open /var/snap/nebula/common/config/config.yaml: permission denied"

ls -l /var/snap/nebula/common/config/
total 12
-r-------- 1 user user 12143 Dec 14 22:03 config.yaml

The documentation talks only about /var/snap/nebula/config, but it looks like it is now /var/snap/nebula/common/config/ -- that is where things like the certificates are now created and it looks like it is looking in that directory for the config.

Sorry if I am missing something obvious!

**Comment by Hooloovoo** [comment]
I knew filing a ticket would mean I figured out the stupid mistake I was making.

I just needed to chown it all to root.

**Comment by jwallden** [comment]
Hello,
Glad you solved it :)
However, you are right about the README. It states /var/snap/nebula/config which is obviously not correct. I'll change that. Thanks for pointing that out.
